// src/components/Post/Post.svelte
<script>
  import FeaturedImage from "./FeaturedImage.svelte";

  export let post;
</script>

<main>
  <article class="BlogPost">
    {#if post.mainImage}
      <div class="BlogPost-image">
        <FeaturedImage image={post.mainImage} />
      </div>
    {/if}

    <div class="l-wide">
      <div class="BlogPost-metadata">
        <h1 class="BlogPost-title">
          <a rel="prefetch" href="posts/{post.slug}">{post.title}</a>
        </h1>

        <time class="BlogPost-date">{post.date}</time>
      </div>
    </div>

    <div class="l-narrow">
      <div class="BlogPost-content">
        <slot />
      </div>
    </div>
  </article>
</main>

// src/screens/Post/Post.tsx
type TODO = any;

export default function Post(props: TODO) {
  const { post } = props;
  // TODO: Featured image
  return (
    <main>
      <article className="BlogPost">
        <div className="l-wide">
          <div className="BlogPost-metadata">
            <h1 className="BlogPost-title">
              <a rel="prefetch" href="posts/{post.slug}">
                {post.title}
              </a>
            </h1>

            <time className="BlogPost-date">{post.date}</time>
          </div>
        </div>

        <div className="l-narrow">
          <div className="BlogPost-content">
            <slot />
          </div>
        </div>
      </article>
    </main>
  );
}
