// src/components/Home/About.svelte
<p class="About-text">
  Hello <span role="img" aria-label="Waving hand">&#x1F44B;.</span> I'm a software
  engineer based in Washington DC. I mainly make things that run in browsers. I currently
  work at <a href="https://www.pbs.org/">PBS</a> as a Principal Engineer to help
  make high quality media accessible.
</p>

// src/screens/Home/About.tsx
export default function HomeAbout() {
  return (
    <p className="About-text">
      Hello{" "}
      <span role="img" aria-label="Waving hand">
        &#x1F44B;.
      </span>{" "}
      I'm a software engineer based in Washington DC. I mainly make things that
      run in browsers. I currently work at{" "}
      <a href="https://www.pbs.org/">PBS</a> as a Principal Engineer to help
      make high quality media accessible.
    </p>
  );
}
