// src/components/Header/index.tsx
import IconGithub from "./IconGithub";

export default function Header() {
  return (
    <div className="Header">
      <div className="l-wide">
        <div className="Header-container">
          <div className="Header-brand">
            <h1 className="Header-title">
              <a className="Header-title-link" href="/">
                Yanglin Zhao
              </a>
            </h1>
            <p className="Header-subtitle">hi (at) yanglinzhao.com</p>
          </div>

          <div className="Header-links">
            <a href="https://github.com/yanglinz">
              <IconGithub width={32} fill="#fff" />
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/Header.svelte
<script>
  import GithubIcon from "./IconGithub.svelte";

  export let segment;

  const isHome = segment === undefined;
</script>

<div class="Header">
  <div class="l-wide">
    <div class="Header-container">
      <div class="Header-brand">
        <h1 class="Header-title">
          <a class="Header-title-link" href="/">Yanglin Zhao</a>
        </h1>
        <p class="Header-subtitle">hi (at) yanglinzhao.com</p>
      </div>

      <div class="Header-links">
        <a href="https://github.com/yanglinz">
          <GithubIcon />
        </a>
      </div>
    </div>
  </div>
</div>
